# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9096f1f5d82629dcae0e78d66538fcc8e629e2d1a5be6ceee5fb18afe352308792f6b21cd1a169ea5385070613e7c18741e31521d8389f744298afd779b6117

test:
  secret_key_base: bcc31783abb44cd45474b4b56e1c5dbdd5d95810a19a66d1e311000adb7a5d0fa44d282d795d205d2ef864f900e3104bcf48e60b03d53cb7deacd2a94c6d385d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
